In [5]:
import pandas as pd
from datetime import datetime
from datetime import timedelta
from api_utils import request_forecast,init_settings

start_date,end_date = init_settings()

In [6]:

df_list = []
start = datetime.strptime(start_date, '%Y-%m-%d').date()
end = datetime.strptime(end_date, '%Y-%m-%d').date()


while (start<=end):
    row = request_forecast(start)
    df_list.append(row)
    start = start + timedelta(days=1)

df = pd.concat(df_list)

In [7]:
df.head()

,date,lat,long,country,city,mintemp_c,maxtemp_c,avgtemp_c,avghumidity,totalprecip_mm,description
0,2023-01-01,-34.59,-58.67,Argentina,Buenos Aires,21.1,27.0,24.2,52.0,8.7,Moderate or heavy rain shower
0,2023-01-02,-34.59,-58.67,Argentina,Buenos Aires,16.3,33.2,24.5,45.0,0.0,Sunny
0,2023-01-03,-34.59,-58.67,Argentina,Buenos Aires,18.8,33.5,26.7,26.0,0.1,Patchy rain possible
0,2023-01-04,-34.59,-58.67,Argentina,Buenos Aires,18.3,31.9,25.0,42.0,0.0,Sunny
0,2023-01-05,-34.59,-58.67,Argentina,Buenos Aires,19.2,34.0,26.3,42.0,0.0,Sunny

In [8]:
df.to_csv(f'data/01_raw/{start_date}_{end_date}.csv',index=False)